kind: PersistentVolume
apiVersion: v1
metadata:
  name: kafka-pv-1
  labels:
    type: local
    app: kafka-pv-1
spec:
        #  storageClassName: nfs-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/kafka/pv1

